# Generated by Django 3.2.7 on 2021-10-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCine', models.CharField(max_length=200)),
                ('direccionCine', models.CharField(max_length=200)),
                ('telefonoCine', models.CharField(max_length=50)),
                ('emailCine', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoSala', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=200)),
                ('id_cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cine')),
                ('id_tipoSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tiposala')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePelicula', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.sala')),
            ],
        ),
    ]
